version: '2.2'
services:
  cerebro:
    image: lmenezes/cerebro:0.8.3
    container_name: cerebro
    ports:
      - "9000:9000"
    command:
      - -Dhosts.0.host=http://elasticsearch:9200
    networks:
      - es7net
  kibana:
    image: docker.elastic.co/kibana/kibana:7.3.0
    container_name: kibana7
    environment:
      - I18N_LOCALE=zh-CN
      - XPACK_GRAPH_ENABLED=true
      - TIMELION_ENABLED=true
      - XPACK_MONITORING_COLLECTION_ENABLED="true"
    volumes:
      - /Users/zhangwei/Documents/es/kibana/logs:/usr/share/kibana/logs
      - /Users/zhangwei/Documents/es/kibana/plugins:/usr/share/kibana/plugins
      - /Users/zhangwei/Documents/es/kibana/config:/usr/share/kibana/config  
    ports:
      - "5601:5601"
    networks:
      - es7net
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.0
    container_name: es7_01
    environment:
      - cluster.name=zhangweiwhimes
      - node.name=es7_01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.seed_hosts=es7_01,es7_02
      - cluster.initial_master_nodes=es7_01,es7_02
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /Users/zhangwei/Documents/es/es7_01/data:/usr/share/elasticsearch/data
      - /Users/zhangwei/Documents/es/es7_01/config:/usr/share/elasticsearch/config
      - /Users/zhangwei/Documents/es/es7_01/logs:/usr/share/elasticsearch/logs
      - /Users/zhangwei/Documents/es/es7_01/plugins:/usr/share/elasticsearch/plugins
    ports:
      - 9200:9200
    networks:
      - es7net
  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.0
    container_name: es7_02
    environment:
      - cluster.name=zhangweiwhimes
      - node.name=es7_02
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.seed_hosts=es7_01,es7_02
      - cluster.initial_master_nodes=es7_01,es7_02
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /Users/zhangwei/Documents/es/es7_02/data:/usr/share/elasticsearch/data
      - /Users/zhangwei/Documents/es/es7_02/config:/usr/share/elasticsearch/config
      - /Users/zhangwei/Documents/es/es7_02/logs:/usr/share/elasticsearch/logs
      - /Users/zhangwei/Documents/es/es7_02/plugins:/usr/share/elasticsearch/plugins
    networks:
      - es7net


volumes:
  es7data1:
    driver: local
  es7data2:
    driver: local

networks:
  es7net:
    driver: bridge
